version: "2"
services:
    elasticsearch:
        image: elasticsearch:6.5.4
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        networks:
            - elasticbridge

    metricbeat:
        image: docker.elastic.co/beats/metricbeat:6.5.4
        volumes:
            - ./config/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - elasticbridge

    kibana:
        image: kibana:6.5.4
        ports: 
            - "5601:5601"
        volumes:
            - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        networks:
            - elasticbridge

networks:
  elasticbridge:
    driver: bridge

