version: "2.1"
services:
    telegraf:
      image: telegraf:1.9.1-alpine
      depends_on:
        - influxdb
      stdin_open: true
      tty: true
      privileged: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys:/rootfs/sys:ro
        - /proc:/rootfs/proc:ro
        - /etc:/rootfs/etc:ro
        - /var/run/utmp:/var/run/utmp
        - ./config/telegraf/telegraf.conf:/root/telegraf.conf:ro

      environment:
        - TELEGRAF_CONFIG_PATH=/root/telegraf.conf
        - OUTPUT_INFLUXDB_ENABLED=true
        - INPUT_DOCKER_ENABLED=true
        - HOST_PROC=/rootfs/proc
        - HOST_SYS=/rootfs/sys
        - HOST_ETC=/rootfs/etc

    influxdb:
      image: influxdb:1.7.2-alpine
      ports:
        - "8086:8086"
        - "8083:8083"
#      volumes:
#        - ./files/influxdb:/etc/influxdb
      environment:
        - FORCE_HOSTNAME=auto
        - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_DB=db0
        - INFLUXDB_HTTP_AUTH_ENABLED=false
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
        - INFLUXDB_USER=dbUser
        - INFLUXDB_USER_PASSWORD=secretpassword
        - INFLUXDB_READ_USER=dbReader
        - INFLUXDB_READ_USER_PASSWORD=password
        - INFLUXDB_WRITE_USER=dbWriter
        - INFLUXDB_WRITE_USER_PASSWORD=password

#        - INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf

    chronograf:
      image: chronograf:1.7.5-alpine
      ports:
        - "8888:8888"
      environment:
        - INFLUXDB_URL=http://influxdb:8086
        - INFLUXDB_USERNAME=dbReader
        - INFLUXDB_PASSWORD=password

    kapacitor:
      image: kapacitor:1.5.2-alpine
      ports:
        - "9092:9092"
      environment:
        - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
        - KAPACITOR_INFLUXDB_USERNAME=dbWriter
        - KAPACITOR_INFLUXDB_PASSWORD=password
        - KAPACITOR_INFLUXDB_ENABLED=true
        - KAPACITOR_INFLUXDB_SUBSCRIPTION_MODE=server
        - KAPACITOR_INFLUXDB_SUBSCRIPTION_PROTOCOL=http
        - KAPACITOR_INFLUXDB_KAPACITOR_HOSTNAME=kapacitor

    grafana:
      image: grafana/grafana:5.4.2
      ports:
        - "0.0.0.0:3000:3000"
      volumes:
        - ./files/grafana:/etc/extra-config/grafana
      environment:
        - GRAFANA_USER=admin
        - GRAFANA_PASS=admin
 
