version: "2.1"
services:
    elasticsearch:
        image: elasticsearch:6.5.4
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:z
            - esdata:/usr/share/elasticsearch/data
        healthcheck:
            test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:${ES_PASSWORD}", "http://localhost:9200/_cat/health"]            
        networks:
            - elasticbridge

    metricbeat:
        image: docker.elastic.co/beats/metricbeat:6.5.4
        depends_on:
            elasticsearch:  { condition: service_healthy }
        command: metricbeat -e -system.hostfs=/hostfs -E output.elasticsearch.username=elastic -E output.elasticsearch.password=${ES_PASSWORD} -strict.perms=false            
        volumes:
            - ./config/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:z
            - ./config/metricbeat/modules.d/docker.yml:/usr/share/metricbeat/modules.d/docker.yml:z
            - ./config/metricbeat/modules.d/kibana.yml:/usr/share/metricbeat/modules.d/kibana.yml:z
            - ./config/metricbeat/modules.d/elasticsearch.yml:/usr/share/metricbeat/modules.d/elasticsearch.yml:z
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /proc:/hostfs/proc:ro
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
        networks:
            - elasticbridge

    kibana:
        image: kibana:6.5.4
        depends_on:
            - elasticsearch
        ports: 
            - "5601:5601"
        healthcheck:
            test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
            retries: 5           
        volumes:
            - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        networks:
            - elasticbridge

#   configure_stack:
#     container_name: configure_stack
#     image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION}
#     volumes: ['./init/configure-stack.sh:/usr/local/bin/configure-stack.sh:ro','./init/pipelines/:/usr/local/bin/pipelines/','./init/templates/:/usr/local/bin/templates/']
#     command: ['/bin/bash', '-c', 'cat /usr/local/bin/configure-stack.sh | tr -d "\r" | bash']
#     networks: ['elasticbridge']
#     environment: ['ELASTIC_VERSION=${ELASTIC_VERSION}','ES_PASSWORD=${ES_PASSWORD}','DEFAULT_INDEX_PATTERN=${DEFAULT_INDEX_PATTERN}']
#     depends_on: ['elasticsearch','kibana']


networks:
  elasticbridge:
    driver: bridge

volumes:
  esdata:
    driver: local

