version: "2"
services:
    prometheus:
        image: prom/prometheus:v2.6.0
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - "9900:9090"
    node-exporter:
        image: prom/node-exporter:v0.17.0
        ports: 
            - "9100:9100"
    pushgateway:
        image: prom/pushgateway
        ports:
            - "9091:9091"
    grafana:
        image: grafana/grafana:5.4.2
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
