cluster.name: "docker-cluster"
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 1
network.host: "elasticsearch1"
discovery.seed_hosts:
  - 172.16.238.10
cluster.initial_master_nodes:
  - elasticsearch1
http.cors.enabled: false
http.cors.allow-origin: "*"

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
xpack.monitoring.collection.enabled: true

