metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch1:9200']
#  username: elastic
#  password: changeme

setup.dashboards.enabled: true

setup.kibana:
  host: "kibana:5601"

metricbeat.modules:
  - module: kibana
    metricsets: ["status"]
    period: 10s
    hosts: ["kibana:5601"]
    basepath: ""
    enabled: true
    
