---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://elasticsearch1:9200"]
xpack.monitoring.ui.container.elasticsearch.enabled: false
xpack.monitoring.enabled: false
xpack.monitoring.kibana.collection.enabled: false
